#%RAML 1.0 NamedExample
  
  - 
    text: "To meet the patient where they are - It's a long-standing concept in the field of medicine, writes Tom. That means universal access for patients and providers, anywhere. Sound familiar? It's our mission here at Science 37."
    url: "https://t.co/Science37Test"
    author: "Science37TestUser"
  -
    text: "Our #DiversityInClinicalTrials business unit’s mission is to collaborate with all who share our vision of eliminating health disparities in underrepresented communities through our patient-centered approach to clinical research."
    url: "https://t.co/AaBbCcDd1234Test"
    author: "tliu301"
